In [1]:
import numpy as np
a = np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [2]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
a = np.array(range(15))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
a = list(range(15))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [5]:
a = np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [6]:
a = np.arange(10, 20, 3)
print(a)

[10 13 16 19]


In [7]:
a = np.arange(5)
print(a[3])
print(a[:3])
print(a[3:])

3
[0 1 2]
[3 4]


In [8]:
a = np.arange(10)
a[3:8] = range(100, 105)
print(a)

[  0   1   2 100 101 102 103 104   8   9]


In [9]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
a = np.random.rand(5)
print(a)

[0.96861303 0.75588473 0.48835698 0.32184315 0.96251909]


In [11]:
a = np.random.randint(5)
print(a)

2


In [12]:
a = np.fromstring('1 2 3 4 5', sep= ' ')
print(a)

a = np.fromstring('1,2,3,4,5', sep= ',')
print(a)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [13]:
a = np.loadtxt('nums.txt', delimiter=',')
print(a)

a = np.loadtxt('nums.txt', usecols=[0], delimiter=',')
print(a)

[[11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]
 [31. 32. 33. 34. 35.]]
[11. 21. 31.]


In [14]:
a = np.arange(5)
print(a)
print(a + 3)
print(a * 3)
print(a / 4)

[0 1 2 3 4]
[3 4 5 6 7]
[ 0  3  6  9 12]
[0.   0.25 0.5  0.75 1.  ]


In [15]:
a = np.arange(5)
b = np.arange(10, 15)
print(a + b)
print(a * b)
print(a ** b)

[10 12 14 16 18]
[ 0 11 24 39 56]
[        0         1      4096   1594323 268435456]


In [16]:
a = np.ones(5) * 10
print(a)

[10. 10. 10. 10. 10.]


In [17]:
a = np.arange(1,5)
print(a)
print(np.sum(a))
print(np.size(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

[1 2 3 4]
10
4
2.5
4
1


In [18]:
a = np.arange(10, 35, 3)
print(a)
print(a[[3,5,7]])
x = np.array([3,5,7])
print(a[x])

[10 13 16 19 22 25 28 31 34]
[19 25 31]
[19 25 31]


In [19]:
a = np.arange(0,5)
print(a)
print(a < 3)
print(a > 3)
print(a == 3)

[0 1 2 3 4]
[ True  True  True False False]
[False False False False  True]
[False False False  True False]


In [20]:
a = np.arange(0,5)
print(a[a<3])
print(a[a>3])
print(a[a==3])
print(a[(a<3) | (a>3)])
print(a[(a>2) | (a<4)])
print(a[~(a==3)])

[0 1 2]
[4]
[3]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2 4]


In [21]:
a = np.arange(10, 35, 3)
print(a)
print(a%2)
print(a[(a%2) == 0])

[10 13 16 19 22 25 28 31 34]
[0 1 0 1 0 1 0 1 0]
[10 16 22 28 34]


In [22]:
a = np.arange(0,5)
print(a)
print(a[(a%2) == 0])
a[(a%2) == 0] = 999
print(a)

[0 1 2 3 4]
[0 2 4]
[999   1 999   3 999]


In [23]:
a = np.array([10, 20, 30])
print(a.dtype)

a = np.array([10, 20.5, 30.7])
print(a.dtype)

a = np.arange(5, dtype=np.float64)
print(a)
print(a.dtype)

a = np.array([1.2, 2.3, 3.4])
b = np.array([4, 5, 6])
c = a * b
print(c)
print(c.dtype)

a = np.array([10, 20, 'abc', 40, 'defg'])
print(a)
print(a.dtype)

int32
float64
[0. 1. 2. 3. 4.]
float64
[ 4.8 11.5 20.4]
float64
['10' '20' 'abc' '40' 'defg']
<U11


In [24]:
a = np.array([10, 20, 30])
a.astype('int64')
print(a)
print(a.dtype)
2**16

[10 20 30]
int32


65536

In [25]:
a = np.nan
print(type(a))
print(np.nan == np.nan)
print(np.nan is np.nan)

a = np.array([1,2,3,np.nan,5])
print(a)
print(np.isnan(a))
print(np.mean(a))
print(np.sum(a))

print(a[np.isnan(a)])
print(a[~np.isnan(a)])
print(np.mean(a[~np.isnan(a)]))

<class 'float'>
False
True
[ 1.  2.  3. nan  5.]
[False False False  True False]
nan
nan
[nan]
[1. 2. 3. 5.]
2.75


In [26]:
# multidimensional
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a[0])
print(a[1])

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [27]:
# grabbing columns
print(a[:,0])
print(a[:,1])
print(a[0,2])

[1 4]
[2 5]
3


In [28]:
# reshaping
a = np.arange(15)
a = a.reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
# transpose
a = np.arange(10).reshape(2, 5)
print(a)
a = a.transpose()
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [30]:
# sorting 
a = np.array([[20,30,25,10], [90,5,70,15]])
a.sort()# same as a.sort(axis=-1)
print(a)# sort as default
a.sort(axis=0)
print(a) # sort as column
a.sort(axis=1)
print(a) # sort as line

[[10 20 25 30]
 [ 5 15 70 90]]
[[ 5 15 25 30]
 [10 20 70 90]]
[[ 5 15 25 30]
 [10 20 70 90]]
